logging:
  level:
    org:
      springframework:
        security: DEBUG
        root: WARN

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
      ansi:
        enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
